### ISSUE TITLE
Architecture Design Document

### ISSUE THREAD

**Issue by chaintng** [kaogeek/fact-finder#12]
ต้องการ Document สำหรับ...
- Overview เล่าการทำงานของ Application
- Architecture Design

คุณ @vtno แนะนำ  https://github.com/mingrammer/diagrams 
สำหรับการสร้าง Diagrams

**Comment by vtno** [comment]
เดี๋ยวผมลองทำง่าย ๆ ให้ครับ

**Comment by tee4cute** [comment]
ทั้ง 2 ข้อน่าจะอยู่ใน PR นี้ https://github.com/kaogeek/fact-finder/pull/15 แล้วหรือเปล่าครับ?

**Comment by chaintng** [comment]
คับ ปิดได้คับ
