### ISSUE TITLE
Overall Project Spec in `README.md`

### ISSUE THREAD

**Issue by tee4cute** [kaogeek/fact-finder#2]
The following info should be provided:

- Project motivations
- What is **Fact Finder**? (and also what is not)
- How **Fact Finder** works!
- Project milstones and scopes
- How to run the code
- How to contribute or how to join the team

**Comment by chaintng** [comment]
i can take this

**Comment by chaintng** [comment]
Should we do these in Thai or English? What do u think?
@tee4cute @vtno

**Comment by tee4cute** [comment]
> Should we do these in Thai or English? What do u think?

@chaintng English would be better (but can do later :)
